app/uk/gov/hmrc/cbcrfrontend/views/subscription/subscribeSuccessCbcId.scala.html
=> style subscribe success page

conf/application.conf
This config is now in app-config-qa as it should not we a default for other environments
=> Corrected the Content Security Policy - removed QA now in yaml

app/uk/gov/hmrc/cbcrfrontend/controllers/CBCController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/Submission.scala, app/uk/gov/hmrc/cbcrfrontend/views/forms/enterCBCId.scala.html, conf/app.routes
1. Changed route so cbcId check comes at the end
2. Changed saveSubscriptionDetails to cacheSubscriptionDetails because it was confusing me
3. Re-ordered routes for enter-cbcId so the reverse router picked up the correct one.
=> Changed route to move cbcId check

app/uk/gov/hmrc/cbcrfrontend/connectors/FileUploadServiceConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadController.scala, app/uk/gov/hmrc/cbcrfrontend/package.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCRXMLValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/FileUploadService.scala, app/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtract.scala, project/FrontendBuild.scala, test/resources/cbcr-invalid-multiple-errors2.xml, test/resources/schema/CbcXML_v1.0.xsd, test/resources/schema/CbcXML_v1.0.xsd.xml, test/resources/schema/isocbctypes_v1.0.xsd, test/resources/schema/oecdtypes_v4.1.xsd, test/uk/gov/hmrc/cbcrfrontend/connectors/FileUploadControllerServiceConnectorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCXMLValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/XmlErrorHandlerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtractSpec.scala
We're now using a new validator for the xml and the business rule
validation has been optimised
=> Added more robust logic around validation

app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSuccessReceipt.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/subscribeSuccessCbcId.scala.html
As per accessibility requirements
=> Updated confirmation pages

app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala
CBCId should not be persisted in Org journey
=> Fixed bug when back button used

app/uk/gov/hmrc/cbcrfrontend/GuiceModule.scala, app/uk/gov/hmrc/cbcrfrontend/config/frontendWiring.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/model/ErrorTypes.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataService.scala, test/resources/cbcr-additionalInfoOECD0-2.xml, test/resources/cbcr-additionalInfoOECD0.xml, test/resources/cbcr-cbcReportsOECD0-2.xml, test/resources/cbcr-cbcReportsOECD0.xml, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
Included rules and tests to check for OECD0 misuse
=> CBCR-670: Added call to PATCH /cbcr/reporting-entity

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/model/ErrorTypes.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataService.scala, conf/messages, test/resources/cbcr-valid-multipleupload.xml, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataServiceSpec.scala
=> DLS-115: Implemented new business rule to prevent multiple file upload for the original submission within the same reporting period

repository.yaml
=> CBCR-879: add repo to services catalogue

app/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadController.scala, conf/test.routes
=> DLS-119: Implemented the test only end point to return the business rule validation errors from cache.

app/uk/gov/hmrc/cbcrfrontend/connectors/test/TestCBCRConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, conf/test.routes, conf/testOnlyDoNotUseInAppConf.routes
=> create test-only endpoint to drop mongo collection

app/uk/gov/hmrc/cbcrfrontend/views/govuk_wrapper.scala.html
=> DLS-95: Removed the beta banner

app/uk/gov/hmrc/cbcrfrontend/views/govuk_wrapper.scala.html
Reverts hmrc/cbcr-frontend#388
=> Revert "DLS-95: Removed the beta banner"

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/views/show_all_docRefIds.scala.html
=> DLS-165: Refactoring

app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala
=> DLS-199: Fixed compilation issue

app/uk/gov/hmrc/cbcrfrontend/views/show_all_docRefIds.scala.html
=> DLS-AdminEndpointChange

app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/views/show_all_docRefIds.scala.html, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
DLS-115v1 - Reverted the multiple file upload change
**Bug fix
=> DLS-115v1 - Reverted the multiple file upload change

app/uk/gov/hmrc/cbcrfrontend/model/XMLInfo.scala
Made a change to the doc ref id format
DLS-200 - Made a change to the doc ref id format
**Bug fix ** (delete as appropriate)
=> DLS-200v1: Made a change to the doc ref id format

project/FrontendBuild.scala, project/plugins.sbt
=> DLS-247: Bootstrap library upgrades

app/uk/gov/hmrc/cbcrfrontend/model/XMLInfo.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
=> DLS-OECD0Change: Added another regex for correction doc ref Id.

app/uk/gov/hmrc/cbcrfrontend/model/ErrorTypes.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, conf/messages, test/resources/cbcr-messageRefId-dontMatchAgainst-messageRefId-inDocRefId.xml, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
Implemented the logic to validate the MessageRefId of DocRefId against the MessageRefId of MessageSpec
=> DLS-261: Implemented the logic to validate the MessageRefId of DocRefId against the MessageRefId of MessageSpec

app/uk/gov/hmrc/cbcrfrontend/model/ErrorTypes.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, conf/messages, test/resources/cbcr-OECD0[1]-invalid1.xml, test/resources/cbcr-messageRefId-dontMatchAgainst-messageRefId-inDocRefId.xml, test/resources/cbcr-valid.xml, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
=> DLS-288: Implemented the logic to validate the MessageRefId of DocRefId against the MessageRefId of MessageSpec

app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
=> Dls 261 new

app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, test/resources/cbcr-OECD0[1]-invalid1.xml, test/resources/cbcr-valid.xml, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
Reverts hmrc/cbcr-frontend#408
=> Revert "Revert "DLS-288: Implemented the logic to validate the MessageRefId of DocRefId against the MessageRefId of MessageSpec""

app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
=> [CU][DLS-522]: Quick fix for multiple file uploads issue

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataService.scala, project/MicroService.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
**Bug fix** (delete as appropriate)
=> DLS-522: Implemented the long term fix for the multiple file upload edge case scenario

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/views/admin_docRefId_Editor.scala.html, conf/app.routes
=> DLS-760:added endpoint to edit docrefId valid status

app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala
=> [CU][DLS-759]:Swapped parameters for test endpoints

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/views/adminEditReportingEntityData.scala.html, conf/app.routes
=> DLS-919: Added new endpoint

project/FrontendBuild.scala
=> DLS-1096: Upgrading libraries and dependencies - FIX 

project/FrontendBuild.scala, test/uk/gov/hmrc/cbcrfrontend/connectors/FileUploadControllerServiceConnectorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/EnrolControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/LanguageControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/StartControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtractSpec.scala, test/uk/gov/hmrc/cbcrfrontend/util/UnitSpec.scala
=> DLS-1157: Removed hmrctest and reimplemented UnitSpec.

app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
=> DLS-admin-endpoint-fix: need to revert this afterwards

app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/views/addReportingEntityPage.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/adminEditReportingEntityData.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/show_all_docRefIds.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/tepm_admin_page.scala.html
=> Dls admin endpoint fix

project/FrontendBuild.scala
DLS-1322 CBC Tax platform update
**Bug fix ** 
CBC Tax platform update -Play-ui version updated to 8.3.0-play-26 (minor)
- []  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
=> DLS-1322  play-ui version update

app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/fileUploadResult.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/subscribeMatchFound.scala.html, conf/messages, conf/messages.cy
Table cqption added
DLS-1396 CBC accessibility issues - tables (recommendation)
**Bug fix ** (delete as appropriate)
As recommended table caption has been included
=> DLS-1396 CBC accessibility issues - tables (recommendation)

conf/application.conf
=> [CU][DLS-1408]:Updated OECD guidance link

project/FrontendBuild.scala
**Bug fix **
Removed Unused Libraries
=> DLS-1032 Review libraries used by CBC

app/uk/gov/hmrc/cbcrfrontend/package.scala, app/uk/gov/hmrc/cbcrfrontend/views/not_authorised_assistant.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/not_authorised_individual.scala.html, test/uk/gov/hmrc/cbcrfrontend/controllers/StartControllerSpec.scala
=> [LG][DLS-2071] Redirecting individual to forbidden page

conf/application.conf
=> [CU][DLS-2141]: Update assets frontend version

build.sbt
=> [CU][DLS-2141]: Fix xml issue

app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSummary.scala.html
=> Made content change to submit summary file

app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSummary.scala.html
=> DLS-2141: Small content change to summary page. 

app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/chooseFile.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSummary.scala.html
=> [CU][DLS-2159]: Fixing accessibility errors

app/uk/gov/hmrc/cbcrfrontend/views/survey/exitSurvey.scala.html
=> [CU][DLS-2159]: Fix h1 for attribute issue

app/uk/gov/hmrc/cbcrfrontend/views/survey/exitSurvey.scala.html
=> [CU][DLS-2159]: Fix duplicate labels issue

build.sbt, project/build.properties, project/plugins.sbt
=> [CU][DLS-2416]: Library upgrades

app/uk/gov/hmrc/cbcrfrontend/views/shared/enterKnownFacts.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/start.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitInfoUltimateParentEntity.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSummary.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitterInfo.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/contactInfoSubscriber.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/survey/exitSurvey.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/update/updateContactInfoSubscriber.scala.html
=> DLS-2641: Accessibility fixes

build.sbt
=> Update build.sbt: Fix bobby rule violation

app/assets/stylesheets/focus.scss, app/assets/stylesheets/palette.scss, app/uk/gov/hmrc/cbcrfrontend/views/govuk_wrapper.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/chooseFile.scala.html, project/plugins.sbt
=> [CU][DLS-2801]: Color/contrast updates

app/assets/stylesheets/focus.scss, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/chooseFile.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/survey/exitSurvey.scala.html
=> DLS-2870 CBC - typography issues

app/uk/gov/hmrc/cbcrfrontend/views/not_authorised_assistant.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/not_authorised_individual.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/shared/enterKnownFacts.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/shared/regenerate.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/shared/sessionExpired.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/start.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/enterCBCId.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/enterCompanyName.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/chooseFile.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/fileUploadError.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/fileUploadProgress.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/fileUploadResult.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/notRegistered.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitInfoUltimateParentEntity.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSuccessReceipt.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSummary.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitterInfo.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/unregisteredGGAccount.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/utrCheck.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/alreadySubscribed.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/contactInfoSubscriber.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/notAuthorised.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/subscribeMatchFound.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/subscribeSuccessCbcId.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/survey/exitSurvey.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/survey/exitSurveyComplete.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/update/contactDetailsUpdated.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/update/updateContactInfoSubscriber.scala.html, conf/messages
=> [CU][DLS-3015]: Updated page titles

app/uk/gov/hmrc/cbcrfrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/cbcrfrontend/config/GenericAppConfig.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/BPRKnownFactsConnector.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/TaxEnrolmentsConnector.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/test/TestCBCRConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/EnrolController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/LanguageController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/StartController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, app/uk/gov/hmrc/cbcrfrontend/services/CreationDateService.scala, build.sbt, conf/application.conf, project/build.properties, project/plugins.sbt, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala
=> [CU][DLS-3034]: Library upgrades + scala 2.12 + sbt version

README.md, app/uk/gov/hmrc/cbcrfrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/cbcrfrontend/util/FeatureSwitch.scala
=> [CU][DLS-3134]: Change whitelist terminology

build.sbt, conf/application.conf
** New feature** (delete as appropriate)
added config for Accessibility Statement
=> DLS-3240 Accessibility-Statement implementation

app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
=> [CU][DLS-3363]: Remove duplicate checks

app/uk/gov/hmrc/cbcrfrontend/model/ErrorTypes.scala, app/uk/gov/hmrc/cbcrfrontend/model/ReportingEntityData.scala, app/uk/gov/hmrc/cbcrfrontend/model/XMLInfo.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtract.scala, app/uk/gov/hmrc/cbcrfrontend/util/BusinessRulesUtil.scala, build.sbt, conf/messages, conf/messages.cy, test/resources/cbcr-full-deletion.xml, test/resources/cbcr-inconsistent-OECD3.xml, test/resources/cbcr-inconsistent-currency-codes.xml, test/resources/cbcr-partial-deletion.xml, test/resources/cbcr-valid-currency-codes.xml, test/resources/cbcr-valid-dup-re-unchanged.xml, test/resources/cbcr-with-fully-corrected-currency.xml, test/resources/cbcr-with-partially-corrected-currency.xml, test/resources/cbcr-withAddInfoCorrRefId.xml, test/resources/cbcr-withCorrRefId.xml, test/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/util/BusinessRulesUtilSpec.scala
=> Stage 1 changes

app/uk/gov/hmrc/cbcrfrontend/model/ReportingEntityData.scala, app/uk/gov/hmrc/cbcrfrontend/model/XMLInfo.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtract.scala, test/resources/cbcr-valid-nonGBTINInDocRefId.xml, test/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/util/BusinessRulesUtilSpec.scala
=> [CU][HTSD-23]: Extract start/end dates + ability to save in the database + backward compatibility

app/uk/gov/hmrc/cbcrfrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/cbcrfrontend/views/ViewHelpers.scala, app/uk/gov/hmrc/cbcrfrontend/views/govuk_wrapper.scala.html, build.sbt, conf/application.conf
=> [CU][DLS-3523]: Use new head element for GTM and update play-ui

app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
HTSD-28 Change in startDate validation rule
Bug fix 
Change in startDate Validation rule
=> HTSD-28 Change in startDate Validation rule

app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/model/SummaryData.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/views/ViewHelpers.scala, app/uk/gov/hmrc/cbcrfrontend/views/govuk_wrapper.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/submission/submitSummary.scala.html, build.sbt, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala
HTSD-UnSignedCommits - To redo the changes on unverified commits
Bug fix
To redo the changes on unverified commits
=> HTSD-UnSignedCommits - To redo the changes on unverified commits

app/uk/gov/hmrc/cbcrfrontend/connectors/test/TestCBCRConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, conf/test.routes
HTSD-33 - Test endpoint created for deleting reportingPeriod
New feature
Test endpoint created for deleting reportingPeriod
=> HTSD-33 - Test endpoint created for deleting reportingPeriod 

app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, conf/application.conf
=> [CU][STAGE-2]: Remove quotes around schema version

app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, conf/application.conf, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala
=> Stage 2 config changes to use bas-gateway-frontend locally instead of company auth

app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/model/FilingType.scala, app/uk/gov/hmrc/cbcrfrontend/model/ReportingRole.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, conf/application.conf, test/resources/cbcr-CBC704-badTIN.xml, test/resources/cbcr-CBC704-badTINAttribute.xml, test/resources/cbcr-OECD0[1]-valid.xml, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala
=> [CU][DCWL-26]: New reporting role + filing type

app/uk/gov/hmrc/cbcrfrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/cbcrfrontend/views/govuk_wrapper.scala.html, conf/application.conf, test/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/StartControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala
=> [CU][DLS-1312]: Remove GA

app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, build.sbt
=> [CU][DLS-3753]: Change continue parameter to continue_url

app/uk/gov/hmrc/cbcrfrontend/config/FrontendAppConfig.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/CBCEnhancementsController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/actions/CBCEnhancementAction.scala, app/uk/gov/hmrc/cbcrfrontend/views/Views.scala, app/uk/gov/hmrc/cbcrfrontend/views/shared/notAuthorisedEnhancement.scala.html, conf/app.routes, conf/application.conf, conf/messages, test/uk/gov/hmrc/cbcrfrontend/controllers/CBCEnhancementsControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/actions/CBCEnhancementActionSpec.scala
**New feature** 
New features added to CBC should only be visible when cbcEnhancementFeature flag is set to true.
=> DAC6-972 - Create featureToggle for CBC changes

app/uk/gov/hmrc/cbcrfrontend/views/Views.scala, app/uk/gov/hmrc/cbcrfrontend/views/notAuthorisedEnhancement.scala.html
**New feature** 
New features added to CBC should only be visible when cbcEnhancementFeature flag is set to true.
=> Dac6 972: Update Layout in cbcEnhancement not authorised view

app/uk/gov/hmrc/cbcrfrontend/views/upscan/uploadError.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/upscan/uploadForm.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/upscan/uploadProgress.scala.html, public/javascripts/poller.js
On receving the upscan status as Rejection redirect to fileInvalid page
=> DAC6-967: redirect to fileInvalid page on rejection

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/services/SubmissionService.scala, app/uk/gov/hmrc/cbcrfrontend/util/XmlLoadHelper.scala, test/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnectorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/SubmissionServiceSpec.scala
Add new end point to submit xml file
=> Add new end point to submit xml file

repository.yaml
=> APPSEC - resolve file level exemptions

app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala
=> DLS-6613 Add Monitoring for the large file upload crash

conf/application.conf
**Bug fix 
Below UI test was failing with Creation date issue.
Scenario: Tina Tax Filer submits valid correction file for original submission that has no creationDate
=> DLS-6649: [RP] Fix for UI tests - Creation date issue.

project/AppDependencies.scala
- moved runtime dependencies from test scope to compile scope
=> DLS-6253: Fixed dependency scopes

app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, app/uk/gov/hmrc/cbcrfrontend/model/SubscriberContact.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtract.scala, app/uk/gov/hmrc/cbcrfrontend/typesclasses/HttpExecutor.scala, build.sbt, test/uk/gov/hmrc/cbcrfrontend/connectors/FileUploadControllerServiceConnectorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/CBCEnhancementsControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/EnrolControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/LanguageControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/StartControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/actions/CBCEnhancementActionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/BPRKnownFactsServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCXMLValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/DocRefIdServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/SubscriptionDataServiceSpec.scala
Reverts hmrc/cbcr-frontend#552
=> Revert "DLS-6253: Update Scala to version 2.13.11"

app/uk/gov/hmrc/cbcrfrontend/controllers/AdminController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, app/uk/gov/hmrc/cbcrfrontend/model/SubscriberContact.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/services/XmlInfoExtract.scala, app/uk/gov/hmrc/cbcrfrontend/typesclasses/HttpExecutor.scala, build.sbt, test/uk/gov/hmrc/cbcrfrontend/connectors/FileUploadControllerServiceConnectorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/CBCEnhancementsControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/EnrolControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/ExitSurveyControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/LanguageControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/StartControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/actions/CBCEnhancementActionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/BPRKnownFactsServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCXMLValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/DocRefIdServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/ReportingEntityDataServiceSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/SubscriptionDataServiceSpec.scala
Reverts hmrc/cbcr-frontend#553
=> Revert "Revert "DLS-6253: Update Scala to version 2.13.11""

app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, project/AppDependencies.scala
- updated bootstrap-frontend library to in order to consume fix for htt-verbs case-insensitivity bug
=> DLS-6253: Bumped bootstrap-frontend dependency to 7.11.0

app/uk/gov/hmrc/cbcrfrontend/views/not_authorised_assistant.scala.html, conf/messages
https://jira.tools.tax.service.gov.uk/browse/DLS-8359
=> DLS-8359 [CBCR] Upgrade not_authorised_assistant

app/uk/gov/hmrc/cbcrfrontend/views/start.scala.html, conf/messages
https://jira.tools.tax.service.gov.uk/browse/DLS-8344
=> DLS-8344 Upgrade start.scala.html template

conf/application.conf
Update for https://jira.tools.tax.service.gov.uk/browse/DLS-8832
=> DLS-8832_link fixing link

conf/application.conf, test/uk/gov/hmrc/cbcrfrontend/services/CreationDateSpec.scala
Adding a11y statement to conf for ticket https://jira.tools.tax.service.gov.uk/browse/DLS-9492
=> DLS-9492 adding a11y statement to conf

app/uk/gov/hmrc/cbcrfrontend/connectors/CBCRBackendConnector.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/FileUploadServiceConnector.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/TaxEnrolmentsConnector.scala, app/uk/gov/hmrc/cbcrfrontend/connectors/test/TestCBCRConnector.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SharedController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/test/TestCBCRController.scala, app/uk/gov/hmrc/cbcrfrontend/package.scala, app/uk/gov/hmrc/cbcrfrontend/repositories/CBCSessionCache.scala, app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala, app/uk/gov/hmrc/cbcrfrontend/views/submission/fileupload/chooseFile.scala.html, app/uk/gov/hmrc/cbcrfrontend/views/subscription/subscribeMatchFound.scala.html, project/AppDependencies.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/FileUploadControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SharedControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionSpec.scala, test/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionControllerSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidatorSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/CBCSessionCacheSpec.scala
- dependency pulls in a high priority OWASP vulnerability - CVE-2022-42889
- library has not seen changes for almost 3 years
- we can and should be using the play config loader
=> DLS-9710: Improve Session/request ID Logging

app/uk/gov/hmrc/cbcrfrontend/controllers/SubmissionController.scala, app/uk/gov/hmrc/cbcrfrontend/controllers/SubscriptionController.scala, app/uk/gov/hmrc/cbcrfrontend/emailaddress/EmailAddress.scala, app/uk/gov/hmrc/cbcrfrontend/emailaddress/ObfuscatedEmailAddress.scala, app/uk/gov/hmrc/cbcrfrontend/emailaddress/PlayJsonFormats.scala, app/uk/gov/hmrc/cbcrfrontend/model/ETMPGetResponse.scala, app/uk/gov/hmrc/cbcrfrontend/model/SubmitterInfo.scala, app/uk/gov/hmrc/cbcrfrontend/services/FileUploadService.scala, conf/application.conf, test/uk/gov/hmrc/cbcrfrontend/emailaddress/EmailAddressSpec.scala, test/uk/gov/hmrc/cbcrfrontend/services/FileUploadServiceSpec.scala
- Revert to old email validator
- Use calendar year when setting expiry date on envelope
=> DLS-11283/Fix CBCR issues

conf/application.conf
Local run verified and build working on cbcr ATs
```
[info] All tests passed.
[success] Total time: 494 s (08:14), completed 6 Mar 2025, 21:05:49
```
=> DLS-11450 | Add missing nonce directive config for csp
